### ISSUE TITLE
A

### ISSUE THREAD

**Issue by Jerrynicki** [nichtdasleo/LeOS9000-Bot#7]
![image](https://user-images.githubusercontent.com/38357030/46580142-922cb300-ca1f-11e8-8b1a-f2d42c5dae7f.png)
![ehrenlos](https://user-images.githubusercontent.com/38357030/46580146-acff2780-ca1f-11e8-815c-2c24e1a1023d.png)

**Comment by nichtdasleo** [comment]
haha ja

**Comment by nichtdasleo** [comment]
vielleicht fixe ich das heute

**Comment by nichtdasleo** [comment]
wenn ich lust habe
