### ISSUE TITLE
hast du jetzt ernsthaft alle channel gelockt

### ISSUE THREAD

**Issue by Jerrynicki** [nichtdasleo/LeOS9000-Bot#9]

**Comment by nichtdasleo** [comment]
![archive](https://user-images.githubusercontent.com/40544875/46747712-404f8b80-ccb2-11e8-9c66-b8ce857da447.PNG)

**Comment by Jerrynicki** [comment]
![image](https://user-images.githubusercontent.com/38357030/46747846-8dcbf880-ccb2-11e8-9cd1-d7467ee4da80.png)

**Comment by TheLastZombie** [comment]
Lol
